spring:
    application:
        name: gameplay-service
    datasource:
        url: jdbc:mysql://localhost:3306/luta-de-classe-db?reconnect=true&useTimezone=true&serverTimezone=UTC
        driverClassName: com.mysql.jdbc.Driver
        password: admin
        username: admin
    jpa:
        hibernate:
            use-new-id-generator-mappings: false
        properties:
            hibernate: {dialect: org.hibernate.dialect.MySQL5InnoDBDialect}

api:
    info:
        title: 'Gameplay-Service'
        description: 'Serviço de gameplay do jogo Luta de Classes'
        version: v1
        termOfService: 'Termos do Serviço'
        contact:
            name: 'Andrews Reis'
            url: null
            email: andrewsdosreis@gmail.com
        license: 'License of Api'
        licenseUrl: null